In [3]:
# importing element tree
# under the alias of ET
import numpy as np
import pandas as pd
import xml.etree.ElementTree as ET
from matplotlib import pyplot as plt
#import ROOT as root
from array import array


Now that we have recorded real data, let's get a handle on processing waveforms to derive the jitter in these LGADs.

In [4]:
# Define a function to readout data from xml file, and return said data as a time list, voltage list, and event number.
def data_readout(file):
    time_list = []
    volt_list = []
    event_list = []
    # Passing the path of the
    # xml document to enable the
    # parsing process
    xmlfile = ET.parse(file)

    # getting the parent tag of
    # the xml document
    parsedxml = xmlfile.getroot()
    counteve=0
    for child in parsedxml:
        counteve=counteve+1
        t_evt=[]
        v_evt=[]
        counter=0
        for child in child[4][2]:
            data_string=child.text
            split_data = data_string.split(',')
            t_step = float(split_data[0])
            v_step = float(split_data[1])
            t_evt.append(t_step)
            v_evt.append(v_step)
            counter=counter+1
            #print(counter, t_step, v_step)
        time_list.append(t_evt)
        volt_list.append(v_evt)
        event_list.append(counteve-1)
    print("end")
    return time_list, volt_list, event_list

In [9]:
# Extract data from our target xml file
time_list, volt_list, event_list = data_readout(NAME OF FILE HERE)

# Let's print out what the extracted data looks like.
time = np.array(time_list)
volt = -1*np.array(volt_list) #voltage sign flipped to ensure waveform peak is positive.
event = np.array(event_list)
print(time) # in ns
print(volt) # in mV
#print(event_list)

end
[[   1.533    2.533    3.533 ... 1022.533 1023.533 1024.533]
 [   1.676    2.676    3.676 ... 1022.676 1023.676 1024.676]
 [   1.604    2.604    3.604 ... 1022.604 1023.604 1024.604]
 ...
 [   1.672    2.672    3.672 ... 1022.672 1023.672 1024.672]
 [   1.674    2.674    3.674 ... 1022.674 1023.674 1024.674]
 [   1.618    2.618    3.618 ... 1022.618 1023.618 1024.618]]
[[ -0.3 -32.3 -60.9 ... -33.1 -56.4 -79.1]
 [ -1.3 -28.8 -57.5 ... -31.  -60.  -81.7]
 [  1.9 -33.  -61.1 ... -29.1 -58.1 -80.6]
 ...
 [  2.2 -32.7 -60.7 ... -30.5 -61.2 -79. ]
 [  0.4 -31.9 -59.3 ... -28.6 -59.3 -82.9]
 [ -2.2 -28.7 -59.9 ... -31.8 -56.9 -83.3]]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 9

With this data in hand, let's visualize some of it.\
Plot at least one of the waveforms (time vs voltage) to check that we're getting some non-negligible signal, and a general idea of what the average pmax and tmax will be.\
Would also be helpful to plot all waveforms on top of one another.\
\
Shown below is a toy example, showing the different attributes of waveforms we will dive into and use throughout the lab.

![image](toy_example.png)

Next, save the tmax and pmax of each event into a list we can access later.

Plotting out the distributions of pmax and tmax could give us a rough idea of what our data looks like from a macroscopic lens. Helps in case something went wrong for some events.

Finally for now, calculate the average waveform, and plot it.

Now, we can calculate jitter for this dataset. There are a few ways to do it, and its execution is an exercise left to the reader.\
\
\
Rise Time = time between 10% of pmax to 90% of pmax in the rising side of the waveform \
SNR = Signal to Noise Ratio = Power of Signal divided by Power of Noise \
Slew Rate = Voltage over time from 10% of pmax to 90% of pmax

$$ Jitter = {Rise Time \over SNR} = {RMS_{Noise} \over Slew Rate} $$

From here on, your team is free to explore more attributes and trends that could be derived from this data.\
If the PIN diode was also used, it should be possible to calculate the gain at different voltages.